name: BikeDrivers Backend Audit

on:
  push:
    branches: [ "main", "testAndQuality-2" ]
  pull_request:
    branches: [ "main", "testAndQuality-2" ]

jobs:
  audit:
    name: Run audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
          coverage: none
              
      # Defining the cache dir in the environment variables of the runner
      - name: Set Up Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
      
      # Defining the cache dir access options
      - name: Caching Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-{{ hashFiles('**/composer.json') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Update composer   
        run: composer self-update

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # Executing the audit and defining its specifications
      - name: Security Audit
        run: composer audit --no-dev --abandoned=report --ignore-severity=low --ignore-severity=medium --format=json --no-ansi > /tmp/security-audit.json
      
      # Retrieving the audit result
      - name: Upload security audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit
          path: /tmp/security-audit.json